# Generated by Django 3.1.4 on 2020-12-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
