# Generated by Django 3.1.4 on 2020-12-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_reader', '0002_auto_20201226_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
