# Generated by Django 3.1.4 on 2021-01-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_reader', '0003_entry_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='og_image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='og_site_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='og_title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='site_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
